//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int L_ID { get; set; }
        public string L_Proto { get; set; }
        public string L_Local_Address { get; set; }
        public string L_Foreign_Address { get; set; }
        public string L_State { get; set; }
        public string L_Pid { get; set; }
        public Nullable<int> E_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
