//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyEntities1 : DbContext
    {
        public CompanyEntities1()
            : base("name=CompanyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companys> Companys { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Logss> Logss { get; set; }
    }
}
